### ISSUE TITLE
Issue with SSL Cert: www. redirecting to https://www., Chrome throwing privacy error 

### ISSUE THREAD

**Issue by clatwell** [vigetlabs/GroundRules#24] opened 2017-07-24 19:28 UTC
I expect that when I go to groundrules.co or www.groundrules.co, I will see the 404 page that Jason set up. Instead, I'm redirected from www. to https://www., then Chrome is throwing a privacy error that I cannot seem to bypass. 

![screen shot 2017-07-24 at 3 16 02 pm](https://user-images.githubusercontent.com/16839493/28540517-a6e8e166-7083-11e7-890a-099a73e2590d.png)

The CMS login page URL works as expected -  groundrules.co/admin correctly redirects to https://groundrules.co/admin/login, and the CMS login prompt displays as expected. 

![screen shot 2017-07-24 at 3 19 37 pm](https://user-images.githubusercontent.com/16839493/28540692-3dac7806-7084-11e7-80d3-dc1dad1217e5.png)

Here's how the DNS is currently configured, if it helps: 

![screen shot 2017-07-24 at 3 26 28 pm](https://user-images.githubusercontent.com/16839493/28540775-8259030c-7084-11e7-914a-51191f7a1a18.png)

Megan, do you mind taking a look at this issue to see if you're able to reproduce this, and if so, what the next steps should be to resolve it?

**Comment by clatwell** [comment] 2017-07-24 19:33
Add'l context: In Safari, the non-www. groundrules.co resolves to the 404 page, as expected. 

![screen shot 2017-07-24 at 3 32 48 pm](https://user-images.githubusercontent.com/16839493/28541010-69dd084a-7085-11e7-8fba-43afb19b4aa8.png)

www.groundrules.co is throwing this error 

![screen shot 2017-07-24 at 3 34 26 pm](https://user-images.githubusercontent.com/16839493/28541114-c7af20d4-7085-11e7-945d-d1a8c777a6f5.png)

**Comment by clatwell** [comment] 2017-07-24 19:48
Did some troubleshooting with @jroodman. Since the desire is for groundrules.co (non-www) to be the primary domain, as a first step, I deleted the www A record and left just the @ A record. I'll check back in a few hours to see if that made a difference after the DNS propogates. We'll need to set up a redirect rule somewhere (the htaccess file?) to properly redirect www to the non-www. I'm not sure if that will just _work_ with this A record change or not.

**Comment by rysospicy** [comment] 2017-07-24 20:29
Without a DNS entry for `www`, those requests will never make it to the server.  We'll need to add that back in, then most likely add a redirect inside Nginx (proxy that sits in front of the Rails application server) to push `www.groundrules.co` to `groundrules.co`.

**Comment by clatwell** [comment] 2017-07-24 20:32
Alrighty, added the `www` entry back!

**Comment by rysospicy** [comment] 2017-07-24 20:45
Pretty sure it's because of the way we're generating our SSL cert (free, which is awesome, through Let's Encrypt).  It's going to take some time to research what exactly needs to be done to make it work -- and also probably to make sure any changes make it back into `server-provisioning`.

I assume this isn't a problem immediately?  Just something to address before launch?

**Comment by benjaminmodayil** [comment] 2017-07-24 20:59
Was the original plan to do QA on the actual live server?

**Comment by clatwell** [comment] 2017-07-25 13:17
@benjaminmodayil - That is my understanding. To my knowledge, there only exists one server. 

@h0tl33t - I don't think it's an immediate problem. I'm unable to access either variation (www or non-www) in Chrome. If others aren't having that issue, and someone can QA the site in Chrome, it shouldn't need to be addressed until launch.

**Comment by rysospicy** [comment] 2017-07-26 18:34
Re-try non-www (https://groundrules.co) in Chrome.  Shouldn't be any problems there, but let me know if it's still not working for you.

**Comment by jroodman** [comment] 2017-07-31 22:18
Was able to add a Cert for www.groundrules.co today with (Ryan and Pat's help). The endpoint has been confirmed to work on multiple machines and among multiple browser types, so I'm going to close this issue out.

**Closed as completed** 2017-07-31 22:18 UTC
